# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'javaJobs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for javaJobs
pod 'Alamofire', '~> 5.0.0-beta.5'
pod 'SwiftyJSON', '~> 4.0'

end
